name: Daily Apartment Scraping
on:
  schedule:
    - cron: '0 9 * * *'  # Ogni giorno alle 9:00 UTC
  workflow_dispatch:  # Per test manuali

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - run: npm install
      - run: npx playwright install chromium
      - run: node scraper.js
      
      - name: Update Gist
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"files\":{\"apartments.json\":{\"content\":\"$(cat results.json | jq -c . | sed 's/"/\\"/g')\"}}}" \
            https://api.github.com/gists/${{ secrets.GIST_ID }}
